### PR TITLE
Add clang format

### PR DESCRIPTION
**Pull request by Olavhaasie**
##  Description
This PR adds a `.clang-format` file provided by [ROS](https://wiki.ros.org/CppStyleGuide). `clang-format` is a tool that auto formats C++ code. It can be run from the root
```bash
find . -name '*.h'  -or -name '*.cpp' | xargs clang-format -i -style=file
```
[CLion](https://www.jetbrains.com/help/clion/clangformat-as-alternative-formatter.html) can use this file to format code automatically for you :confetti_ball: .

Most of the code was already following this format. Most changes were done automatically and no functionality was changed. :100: 

## Changes
* Add [`.clang-format`](https://github.com/davetcoleman/roscpp_code_format) :fast_forward: 
* Make c++ code adhere to [ROS cpp style guide](https://wiki.ros.org/CppStyleGuide) :man_office_worker: 
* Remove filters from `roslint` :woman: 
* Add Travis job to check `clang-format` :robot: 
* Rename files from _camelCase_ to _under_scored_ :arrow_down:

### CODE REVIEW

**Comment by Roelemans** [comment]
What does "Remove filters from roslint" mean?

**Comment by Ishadijcks** [comment]
Make sure Travis doesn't actually format the code itself :sweat_smile:

**Comment by Roelemans** [comment]
Ik krijg hem niet aan de praat :/. Na pullen, ws cleanen en builden krijg ik de error

roel@roel-HP-ZBook-15:~/colcon_ws$ find . -name '*.h'  -or -name '*.cpp' | xargs clang-format -i -style=file
xargs: clang-format: No such file or directory
roel@roel-HP-ZBook-15:~/colcon_ws$ find . -name '*.h'  -or -name '*.cpp' | xargs .clang-format -i -style=file
xargs: .clang-format: No such file or directory

**Comment by Olavhaasie** [comment]
> What does "Remove filters from roslint" mean?

The `roslint` config applied these filters:

    --filter=-build/include,-build/header_guard,-runtime/references

Which excluded some checks, so I removed them.


> Make sure Travis doesn't actually format the code itself sweat_smile

Haha no the industrial CI script uses [`clang_format_check`](https://github.com/cloderic/clang_format_check), which outputs a diff of required changes.

> Ik krijg hem niet aan de praat :/. Na pullen, ws cleanen en builden krijg ik de error
> 
> roel@roel-HP-ZBook-15:~ /colcon_ws$ find . -name '_.h' -or -name '_.cpp' | xargs clang-format -i -style=file
> xargs: clang-format: No such file or directory
> roel@roel-HP-ZBook-15:~/colcon_ws$ find . -name '_.h' -or -name '_.cpp' | xargs .clang-format -i -style=file
> xargs: .clang-format: No such file or directory

Sorry forgot to mention that you should install `clang-format`

    sudo apt install clang-format

**Comment by Roelemans** [comment]
Nice! It works now for me. Can you make documentation containing 1) How to install 2) the command for execution 3) that it should be run from the root of the repo, not the root of the ws. Maybe also 4) How to make adjustements to the format.

**Comment by Olavhaasie** [comment]
> Nice! It works now for me. Can you make documentation containing 1) How to install 2) the command for execution 3) that it should be run from the root of the repo, not the root of the ws. Maybe also 4) How to make adjustements to the format.

I added a section to the README

**Comment by Ishadijcks** [comment]
It can be useful to install the Pre commit hook plugin in CLion!

It runs a bash script before you can commit. You can use it to run the linter pre-commit to not waste travis builds.

https://plugins.jetbrains.com/plugin/9278-pre-commit-hook-plugin

**Pull request merged**
