### PR TITLE
Set k_postion of ankles to 5.0.

### PR DESCRIPTION
**Pull request by Roelemans**
k position to 5 for ankles. This in necessary to disable wiggles and enable walking.

### CODE REVIEW

**Comment by Roelemans** [comment]
But then we can't train :(

**Comment by Olavhaasie** [comment]
Closing this for now, since this requires more research

**Comment by Roelemans** [comment]
@Deakensbubbles I think we should merge this. 5.0 is not safe, but 0.44 is even more unsafe (wiggles). We should than find a better solution as quickly as possible.

**Comment by Roelemans** [comment]
You are a hero! :tada:

**Pull request merged**
