### PR TITLE
Add custom message for step height and length.

### PR DESCRIPTION
**Pull request by Roelemans**
Related to PM-49

## Description

Add a message containing step height and length. This message is used in the gait generator. 

## Changes

* Added the message FeetDistances.msg

### CODE REVIEW

**Comment by Olavhaasie** [comment]
Why does this have to be a message?

**Comment by Ishadijcks** [comment]
Is the gait generator finally being split into a client-server model like the gait selection? :heart_eyes:

**Comment by Roelemans** [comment]
@Olavhaasie because a seperate node reads out tf frames to calculate the distances between the feet. This then has to be sent to the gait_generator node, I use this message for that purpose. If you have a suggestion for an alternative implementation, please let me know :)

**Comment by Roelemans** [comment]
No longer necessary with new implementation in https://github.com/project-march/gait-generation/pull/69

**Pull request closed without merging**
