### PR TITLE
Feature/pm 393 correct height imu tf

### PR DESCRIPTION
**Pull request by RutgerVanBeek**
Closes PM-393

## Description

This makes sure that when the robot to world transform is made by the IMU that the correct height is set. The height is chosen such that the lowest foot is on the ground. This worked better then I expected, when I moved the IMU quite a lot, it felled really natural. The body still under the ground when you flip the IMU over but I think it does not makes sense the cover that situation, because if exo is upside down we have a lot bigger problems. 
## Changes

* Changed the transformation calculated based on the IMU to take the height of the feet into account and place the exo on the ground. 

## Testing
In the bag find there is some IMU data to test this.

### CODE REVIEW

**Comment by Olavhaasie** [comment]
Is there a ROS way of simulating an IMU?

**Comment by RutgerVanBeek** [comment]
> Is there a ROS way of simulating an IMU?

You mean in Gazebo or for testing this?
If you really want to test it, I can record some IMU data and store it in an bag file.

**Comment by Olavhaasie** [comment]
> If you really want to test it, I can record some IMU data and store it in an bag file.

Could you record some data and share it here? :innocent: I would like to see it

**Comment by RutgerVanBeek** [comment]
[2020-04-07-16-34-57.zip](https://github.com/project-march/march/files/4445205/2020-04-07-16-34-57.zip)

**Pull request merged**
